name: gh-pages.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
          hugo-version: 0.93.0
      - id: extract_branch
        name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
      - id: measurement-4
        name: Record Measurement After Extract branch name
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Extract branch name
          task: get-measurement
      - name: Run a multi-line scripts
        run: 'cd $GITHUB_WORKSPACE/docs-site

          npm install postcss-cli@8.3.0

          base_url="baseURL = \"https://$GITHUB_REPOSITORY_OWNER.github.io/kubeflow-aks/$(git
          branch --show-current)\""

          sed -i "1s#.*#$base_url#" config.toml

          hugo

          '
      - id: measurement-6
        name: Record Measurement After Run a multi-line scripts
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run a multi-line scripts
          task: get-measurement
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/public
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
